### ISSUE TITLE
Buckets are getting rotated for every new workload deployment

### ISSUE THREAD

**Issue by sivachunduru** [oracle-quickstart/oci-landing-zones#40]
Every time a new workload is being deployed, we end up populating "workload_compartment_names" and "additional_workload_subnets_cidr_blocks" values of both the environments in enterprise landing zone template and re-applying the TF. This is forcing buckets to be rotated and errors out stating "409-BucketNotEmpty, Bucket named 'TE_P_defaultLogs_standard' is not empty. Delete all object versions first". This error force the user to delete the retention rules, purge the objects in all defaultLogs, auditLogs and serviceEvents buckets. In production environments, loosing the data is advisable. What is the workaround to overcome this issue?

**Comment by paulmuah** [comment]
Issue was resolved by @VinayKumar611. Code updated with fix.

**Comment by pathaknikhil87** [comment]
@paulmuah The issue is still seen in latest OCI-Landing_zones code.
i have updated my error log in https://github.com/oracle-quickstart/oci-landing-zones/issues/44
